#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

export PYTHON_PATH="$SPKG_LOCAL"/bin/python

./configure --prefix="$SPKG_LOCAL" \
    --with-zlib="$SPKG_LOCAL" \
    --with-curl="$SPKG_LOCAL" \
    --without-tcltk
make
make install
